Vagrant.configure("2") do |config|
  config.vm.box_check_update = false

  config.vm.define "windows_vm" do |windows|
    windows.vm.box = "StefanScherer/windows_2019"
    windows.vm.communicator = "winrm"
    windows.vm.provision "shell", path: "provision.sh"
    windows.vm.boot_timeout = 600
    windows.vm.network :forwarded_port, guest: 3389, host: 3390, id: "rdp", auto_correct: true
  end

  config.vm.define "linux_vm" do |linux|
    linux.vm.box = "ubuntu/bionic64"
    linux.vm.boot_timeout = 600  # Set timeout to 10 minutes
    linux.vm.provision "shell", path: "provision.sh"
  end
end

